import React from 'react';
import Message from './Message';

export default function MessageList({messages}) {

  return (
    <div>
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
        MyMessages...
    </div>
  );
}